name: QA

on:
  push:
  workflow_dispatch:

jobs:
  qa-checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ["25", "26", "27"]
        rebar3: ["3.24"]

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Setup Beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}

      - name: Run Lint
        env:
          ERL_FLAGS: "-enable-feature all"
        run: rebar3 fmt --check

      - name: Run Tests
        env:
          ERL_FLAGS: "-enable-feature all"
        run: rebar3 test
